version: "3.2"

services:
  api-verzel-auto:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-verzel-auto
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - mongodb
    hostname: localhost
    command: npm run dev:server
   
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    hostname: localhost
